// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB906pZoiyaCdAn_kKGzuG401qM3nk2bY',
    appId: '1:795736347809:web:c3bdf8f7937bb3452d8ce0',
    messagingSenderId: '795736347809',
    projectId: 'unihapps',
    authDomain: 'unihapps.firebaseapp.com',
    storageBucket: 'unihapps.firebasestorage.app',
    measurementId: 'G-5DPCWL0241',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPPQm-b_P9dqB99bEdVGiaTVOkNbKXaqg',
    appId: '1:795736347809:android:896db0d8f041f8c12d8ce0',
    messagingSenderId: '795736347809',
    projectId: 'unihapps',
    storageBucket: 'unihapps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9cJYEQYOtAe1bVxGgY0HQF4bPuudEAt0',
    appId: '1:795736347809:ios:f8c68f09c290099f2d8ce0',
    messagingSenderId: '795736347809',
    projectId: 'unihapps',
    storageBucket: 'unihapps.firebasestorage.app',
    iosBundleId: 'com.example.unihapps',
  );
}